### ISSUE TITLE
Why term.onKey?

### ISSUE THREAD

**Issue by jerch** [jmmv/endbasic#22]
Congrats, this is a really nice example how to get cmdline tools into web realms with wasm and xterm.js. The blocking I/O is really a showstopper for easy ports of most apps, also the wasm env still lacks several POSIX layers, but I guess this will change over time (emscripten already shims FS parts for C apps).

On thing that bugs me in xterm.js snippets seen all over the internet - is there a specific reason to use `onKey` handler with xterm.js instead of `onData`? The latter would give you a character stream as on stdin of a console app (on a raw terminal, thus still lacking echoing, erase - things done by the missing pty). `onData` would also handle c&p and meta keys correctly, while `onKey` is on a very raw edge.

**Comment by jmmv** [comment]
Hey @jerch, thanks for the feedback!

The reason I used `onKey` is because the example in the Xterm.js front page does that: https://xtermjs.org/js/demo.js . I suspect that's why a lot of the code you see around does the same...

I'll take a look at this `onData` thing. I'm really a newbie in the JavaScript world so I don't know anything about best practices! Will keep this open until I do.

**Comment by jerch** [comment]
> The reason I used onKey is because the example in the Xterm.js front page does that: https://xtermjs.org/js/demo.js . I suspect that's why a lot of the code you see around does the same...

Eww, never looked at that code before -  thanks for the pointer, guess we should change that.
